#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details
#

# Only run CI builds for these branches
trigger:
  branches:
    include:
    - 'master'
    - 'release/*'
    - 'internal/release/*'
# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

name: $(Date:yyyyMMdd).$(Rev:rr)

jobs:
- template: eng/common/templates/jobs/jobs.yml
  parameters:
    agentOs: Windows
    configuration: Release
    codeSign: true
    publishToBar: true
    artifacts:
      publish: true
      name: artifacts
      path: artifacts/

    - job: Linux
      container: LinuxContainer
      pool:
        ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
          name: dnceng-linux-external-temp
        ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          name: dnceng-linux-internal-temp
      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: none
            _DotNetPublishToBlobFeed : false
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: none
            _DotNetPublishToBlobFeed : false
      steps:
      - checkout: self
        clean: true
      - script: eng/common/cibuild.sh
          --configuration $(_BuildConfig)
          --prepareMachine
        displayName: Unix Build / Publish
