trigger:
- dev
- release/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: AspNetCI GitHub
    name: aspnet/buildtools
    ref: refs/heads/namc/templates
    
phases:
- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: macOS
- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: Windows
- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: Linux
